# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Track Stale Issues

on:
  schedule:
  - cron: '33 6 * * *'

permissions: read-all

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        days-before-stale: 90
        days-before-close: 30
        stale-issue-message: 'No activity with issue for 90 days.'
        stale-pr-message: 'No activity with pull request for 90 days.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        close-issue-message: 'No activity for 120 days.  Will not fix.'
        close-pr-message: 'No activity for 120 days.  Will not merge.'
        close-issue-label: 'wontfix'
        close-pr-label: 'wontfix'
